### ISSUE TITLE
registry remapping failed

### ISSUE THREAD

**Issue by liuyujielol** [skyrising/skyblock#10]
I'm using **fabric-carpet-1.15.2-1.3.17+v200401** and **skyblock-fc-1.15.2-1.1.1** on my local 1.15.2 fabric server, when starting up, it warns that "  **[Server thread/WARN]: Missing data pack fabric/quickcarpet**",
and when I try to enter the game, it shows this:
![skyblock_remapping_error](https://user-images.githubusercontent.com/19249377/78387108-591fcf80-7611-11ea-84d2-03f940e72bef.jpg)

I Gooled a little bit, but I'm not getting much useful information. And I checked twice that I AM using the "-fc" version so I got quite confused why it warns me that I'm "Missing data pack fabric/quickcarpet"
By the way there's no other jar file in the **/mods/** except fabric-api-0.5.1+build.294-1.15.jar

**Comment by skyrising** [comment]
The missing data pack likely happens because you used quickcarpet with this world before? Pretty sure you can ignore that warning.
The registry mapping error happens because you have the Fabric API installed on the client and the server but you don't have the skyblock mod on the client.
If you have no other mod requiring the API on the server you can remove it from there since fabric-carpet and skyblock don't need it. If you can't remove the API from the server or client you need the skyblock mod on the client as well.

**Comment by liuyujielol** [comment]
Aftering removing the API the problem disappears. Guess I just learned another point about the Fabric loader and the Fabric API. xD
//closing issue

**Comment by Quix1** [comment]
> Das fehlende Datenpaket ist wahrscheinlich darauf zurückzuführen, dass Sie Quickcarpet schon einmal mit dieser Welt verwendet haben? Diese Warnung können Sie sicher ignorieren. Der Registrierungsfehler tritt auf, weil Sie die Fabric-API auf dem Client und dem Server installiert haben, aber nicht den Skyblock-Mod auf dem Client haben. Wenn Sie keine andere Mod haben, die die API auf dem Server benötigt, können Sie sie von dort entfernen, da Fabric-Carpet und Skyblock sie nicht benötigen. Wenn Sie die API nicht vom Server oder Client entfernen können, benötigen Sie auch den Skyblock-Mod auf dem Client.

what do you mean by Fabric api the mod or something else
