### ISSUE TITLE
Random Ticks Seem to be Broken on First Launch

### ISSUE THREAD

**Issue by grabage321** [skyrising/skyblock#39]
When loading a world for the first time, random ticks don't work at all.

In the case of decaying leaves, it appears to still spawn the items ~1000 blocks up (while the leaf blocks exist), which can be seen in this video.
https://user-images.githubusercontent.com/70022349/150266381-2f53c394-a07c-4932-96d8-3eeac18c017d.mp4

This issue is fixed on server restart / singleplayer world reload.
This issue is not present in version 3.2.0.

Using QuickCarpet 3.3.0 and Skyblock 3.2.1 with Fabric Loader 0.12.12 for Minecraft 1.18.1.

**Comment by PrivacyPolicy** [comment]
Can confirm this is happening not just on first load, but for every newly-generated chunk.
Reproduce:
1. Open an already-existing creative world
2. Set randomTickSpeed to 3000
3. Teleport to a new chunk
4. Place a copper block, confirm it doesn't oxidize
5. Teleport away to unload the chunks
6. Teleport back to the copper block, it should now start to oxidize

Good find! I'll look into it and see if I can determine the root cause
